## P25-35

In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
a.ndim, np.ndim(a)

(3, 3)

In [4]:
a.shape

(2, 3, 4)

In [5]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a[1][0][0]

12

In [7]:
b = np.linspace(0, 100, 5)
b

array([  0.,  25.,  50.,  75., 100.])

In [8]:
b.shape

(5,)

In [9]:
b[3]

75.0

In [10]:
c = np.logspace(1, 3, 12).reshape(3, 4)
c

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [  53.36699231,   81.11308308,  123.28467394,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [11]:
c.shape

(3, 4)

In [12]:
c[1]

array([ 53.36699231,  81.11308308, 123.28467394, 187.38174229])

In [13]:
c[1][2]

123.28467394420659

In [14]:
c[(1, 2)]

123.28467394420659

In [15]:
b[1] = 100
b

array([  0., 100.,  50.,  75., 100.])

In [16]:
c

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [  53.36699231,   81.11308308,  123.28467394,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [17]:
c[1] = 100
c

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [ 100.        ,  100.        ,  100.        ,  100.        ],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [18]:
c[0, 2] = 99
c

array([[  10.        ,   15.19911083,   99.        ,   35.11191734],
       [ 100.        ,  100.        ,  100.        ,  100.        ],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [19]:
b[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [20]:
c[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [21]:
three = b[0], b[2], b[3]    #如果试图用b[0, 2, 3]，肯定会报错，读者能理解其原因吗？
three

(0.0, 50.0, 75.0)

In [22]:
three2 = b[[0, 2, 3]]
three2

array([ 0., 50., 75.])

In [23]:
b[(0, 2, 3)]

IndexError: too many indices for array

In [24]:
b[[2]]

array([50.])

In [25]:
three2[1] = 999
three2

array([  0., 999.,  75.])

In [26]:
c

array([[  10.        ,   15.19911083,   99.        ,   35.11191734],
       [ 100.        ,  100.        ,  100.        ,  100.        ],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [27]:
c[[0, 2]]

array([[  10.        ,   15.19911083,   99.        ,   35.11191734],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [28]:
c[[0,2], [1,2]]

array([ 15.19911083, 657.93322466])

In [29]:
c[0, 1], c[2, 2]

(15.199110829529339, 657.9332246575682)

In [30]:
b[[2, 2, 2, 2]]

array([50., 50., 50., 50.])

In [31]:
v = np.array([0, 1, 3])
r = b[v]
r

array([  0., 100.,  75.])

In [32]:
b[np.array([2, 3, 2, 3, 2, 3])]

array([50., 75., 50., 75., 50., 75.])

In [33]:
c[np.array([1,2])]

array([[ 100.        ,  100.        ,  100.        ,  100.        ],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [34]:
c[np.array([1, 2]), np.array([0, 1])]

array([100.        , 432.87612811])

In [35]:
b

array([  0., 100.,  50.,  75., 100.])

In [36]:
t = b == 50
t

array([False, False,  True, False, False])

In [37]:
b[t]

array([50.])

In [38]:
e = np.arange(10).reshape(2,5)
t = e % 2 == 0
e[t]

array([0, 2, 4, 6, 8])

In [39]:
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
t2 = np.array([False, True])
e[t2]

array([[5, 6, 7, 8, 9]])

In [41]:
e[e>6]

array([7, 8, 9])

In [42]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
b = a[2: 8]
b

array([12, 13, 14, 15, 16, 17])

In [44]:
b[0] = 12000
b

array([12000,    13,    14,    15,    16,    17])

In [45]:
a

array([   10,    11, 12000,    13,    14,    15,    16,    17,    18,
          19])

In [46]:
a[: : 2]

array([   10, 12000,    14,    16,    18])

In [47]:
a[3:]

array([13, 14, 15, 16, 17, 18, 19])

In [48]:
a[: : -1]

array([   19,    18,    17,    16,    15,    14,    13, 12000,    11,
          10])

In [49]:
a[: 6 : 3]

array([10, 13])

In [50]:
b = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [51]:
b[1: 4]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [52]:
b[1: 4, 2: 5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [53]:
b[0]

array([0, 1, 2, 3, 4, 5])

In [54]:
b[1, :]

array([10, 11, 12, 13, 14, 15])

In [55]:
b[: , 2]

array([ 2, 12, 22, 32, 42, 52])

In [56]:
b[0 : 2, 0 : 2]

array([[ 0,  1],
       [10, 11]])

In [57]:
b[: : 2, : : 2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [58]:
b[: 3 , [0, 3]]

array([[ 0,  3],
       [10, 13],
       [20, 23]])