## P36-45

In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(10).reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a = np.arange(10)
b = np.reshape(a, (2,5))

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
a.shape

(10,)

In [7]:
b.shape

(2, 5)

In [8]:
c = np.reshape(b, (-1, 1))
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [9]:
c = np.reshape(b, (-2, 1))

In [10]:
np.reshape(b, (10,))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.reshape(b, (1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
b.shape

(2, 5)

In [14]:
b.shape = (1, 10)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
b.shape = (10, 1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
p = b.flatten()
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b.reshape((1, 10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [18]:
import numpy as np
ne = np.ravel(b)
ne

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ne[1] = 111
ne

array([  0, 111,   2,   3,   4,   5,   6,   7,   8,   9])

In [20]:
b

array([[  0],
       [111],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [21]:
data = np.arange(0, 5)
c = data[:, np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [22]:
data[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [23]:
data.ndim

1

In [24]:
c.ndim

2

In [25]:
d = data[np.newaxis, :]
d

array([[0, 1, 2, 3, 4]])

In [26]:
d.ndim

2

In [27]:
data.shape, d.shape

((5,), (1, 5))

In [28]:
data2 = np.expand_dims(data, axis=0)
data2

array([[0, 1, 2, 3, 4]])

In [29]:
data2.shape

(1, 5)

In [30]:
data3 = np.expand_dims(data, axis=1)
data3

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [31]:
data3.shape

(5, 1)

In [32]:
a = np.arange(9).reshape(3, 3)
b = np.arange(12).reshape(3, 4)
c = np.arange(15).reshape(3, 5)

In [33]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [34]:
np.hstack((a, b, c))

array([[ 0,  1,  2,  0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 3,  4,  5,  4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 6,  7,  8,  8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [35]:
np.stack((a, b), axis=1)

ValueError: all input arrays must have the same shape

In [36]:
np.concatenate((a, b), axis=1)  #横向叠加，与hstack一样的效果

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [37]:
m = a * 3
a.shape == m.shape

True

In [38]:
np.stack((a, m), axis=1)

array([[[ 0,  1,  2],
        [ 0,  3,  6]],

       [[ 3,  4,  5],
        [ 9, 12, 15]],

       [[ 6,  7,  8],
        [18, 21, 24]]])

In [39]:
a.shape, b.shape

((3, 3), (3, 4))

In [40]:
b2 = b.T
b2.shape

(4, 3)

In [41]:
np.vstack((a, b2))  #纵向叠加

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [42]:
np.concatenate((a, b2), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [43]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
b = a * 3
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  3],
        [ 2,  6]],

       [[ 3,  9],
        [ 4, 12],
        [ 5, 15]],

       [[ 6, 18],
        [ 7, 21],
        [ 8, 24]]])

In [45]:
one = np.arange(5)
two = np.arange(5, 10)
np.column_stack((one, two))

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [46]:
np.row_stack((one, two))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
np.split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [49]:
np.split(a, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [50]:
  np.hsplit(a, 2) #将a横向划分为两个数组

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [51]:
np.vsplit(a, 2)  #将a纵向划分为两个数组

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [52]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])
a.ndim, b.ndim

(2, 2)

In [53]:
r = np.append(a, b, axis=0)
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b

array([[7, 8, 9]])

In [56]:
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a1 = a.flatten()  #表示将a用一个列表展示
a1

array([1, 2, 3, 4, 5, 6])

In [58]:
r = np.insert(a1, 1, 99)
r

array([ 1, 99,  2,  3,  4,  5,  6])

In [59]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.delete(a, 1, axis=0) #由于a是个二维的数组，纵向删除索引为1的数组

array([[1, 2, 3]])