## P46-53  
### 运算和通用函数

In [1]:
lst = [1, 20, 28, 37, 18, 56]
[i*3 for i in lst]

[3, 60, 84, 111, 54, 168]

In [2]:
import numpy as np  
a = np.array(lst)  
a * 3

array([  3,  60,  84, 111,  54, 168])

In [3]:
a = np.arange(10).reshape((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b = a + 10
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
a - 10

array([[-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1]])

In [6]:
a / 10

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [7]:
a.shape == b.shape

True

In [8]:
a + b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [9]:
a - b

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [10]:
a * b

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [11]:
a / b

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

In [12]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
m = np.arange(5)
m

array([0, 1, 2, 3, 4])

In [14]:
a + m

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [15]:
n = np.arange(1, 3).reshape((-1, 1))
a + n

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [16]:
np.array([6, 4, 3]) > np.array([9, 5, 1])

array([False, False,  True])

In [17]:
np.array([6, 4, 3]) > np.array([9, 5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [18]:
np.logical_or(np.array([False, True]), np.array([True, False]))

array([ True,  True])

In [19]:
x = 3
y = 5
x < y and x > y

False

In [20]:
a = np.array([3,6,9])
b = np.array([4, 5, 8])
a < b and a > b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [21]:
np.any(a<b) and np.any(a>b)

True

In [22]:
np.all(a<b)

False

In [23]:
(a<b).all()

False

In [24]:
alpha = np.linspace(-1, 1, 11)
y = np.sin(np.pi * alpha)
np.round(y, decimals=3)

array([-0.   , -0.588, -0.951, -0.951, -0.588,  0.   ,  0.588,  0.951,
        0.951,  0.588,  0.   ])

In [25]:
a, b

(array([3, 6, 9]), array([4, 5, 8]))

In [26]:
np.add(a, b)

array([ 7, 11, 17])

In [27]:
np.add(np.power(np.sin(alpha), 2), np.power(np.cos(alpha), 2))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.sin(alpha)**2 + np.cos(alpha)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
a = np.arange(10.0, 100.0, 2)
b = np.logspace(2, 4, a.shape[0])
m = np.empty_like(a)
a.dtype, b.dtype, m.dtype

(dtype('float64'), dtype('float64'), dtype('float64'))

In [30]:
np.remainder(b, a, out=m)

array([ 0.        ,  3.03363182, 11.28467394,  8.88745095,  7.9911083 ,
        8.76124758, 11.38174229, 16.05675382, 23.01297001,  4.50209057,
       14.80358684, 28.22776602, 11.11917342, 29.86037025, 14.87612811,
        0.63808631, 29.66992312, 20.55309755, 13.93322466, 10.52715427,
       11.13083079, 16.62802021, 28.        , 46.33631817, 14.84673944,
       48.87450954, 31.91108295, 23.61247579, 25.81742286, 40.56753822,
        0.12970008, 45.02090568, 36.03586844, 46.27766017,  1.19173422,
       58.60370255, 64.76128108, 18.38086306,  4.69923121, 29.53097555,
        9.33224658, 37.27154266, 27.3083079 , 78.28020211,  4.        ])

In [31]:
m

array([ 0.        ,  3.03363182, 11.28467394,  8.88745095,  7.9911083 ,
        8.76124758, 11.38174229, 16.05675382, 23.01297001,  4.50209057,
       14.80358684, 28.22776602, 11.11917342, 29.86037025, 14.87612811,
        0.63808631, 29.66992312, 20.55309755, 13.93322466, 10.52715427,
       11.13083079, 16.62802021, 28.        , 46.33631817, 14.84673944,
       48.87450954, 31.91108295, 23.61247579, 25.81742286, 40.56753822,
        0.12970008, 45.02090568, 36.03586844, 46.27766017,  1.19173422,
       58.60370255, 64.76128108, 18.38086306,  4.69923121, 29.53097555,
        9.33224658, 37.27154266, 27.3083079 , 78.28020211,  4.        ])

In [32]:
def bmi(height, weight):
    bmi_index = weight / height ** 2
    if bmi_index >18 and bmi_index < 25:
        return 0
    elif bmi_index <= 18:
        return -1
    else:
        return 1
bmi(1.55, 45)

0

In [33]:
h  = (2.2 - 1.4)* np.random.random_sample((10,)) + 1.4
h = np.round(h, 2)
w = (96 - 30) * np.random.random_sample((10,)) + 30
w = np.round(w, 2)

In [34]:
bmi(h, w)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [35]:
np.array([bmi(h[i], w[i]) for i in range(len(h))])

array([-1,  0,  1,  0,  0,  0, -1,  0,  1, -1])

In [36]:
bmi_ufunc = np.frompyfunc(bmi, 2, 1)
bmi_ufunc(h, w)

array([-1, 0, 1, 0, 0, 0, -1, 0, 1, -1], dtype=object)

In [37]:
pow_ufunc = np.frompyfunc(pow, 2, 1)
a = np.arange(10)
pow_ufunc(a, a)

array([1, 1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489],
      dtype=object)

In [38]:
a ** a

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [39]:
bmi_ufunc2 = np.vectorize(bmi, otypes=[np.float])
bmi_ufunc2(h, w)

array([-1.,  0.,  1.,  0.,  0.,  0., -1.,  0.,  1., -1.])