## P54-56

In [1]:
import numpy as np
mu, sigma = 0.0, 1.0
g = np.random.normal(loc=mu, scale=sigma, size=1000)

In [2]:
g1 = np.random.randn(1000)

In [3]:
g = (g - g.min()) / 10
phy = np.round(((100.1 - 20) * g + 20), 1)
g1 = (g1 - g1.min()) / 10
mat = np.round(((100.1 - 20) * g1 + 20), 1)

In [4]:
np.mean(phy)

49.36789999999999

In [5]:
np.std(phy)

7.918626117578731

In [6]:
np.min(phy), np.max(phy)

(20.0, 72.2)

In [7]:
np.percentile(phy, 80)

56.1

In [8]:
np.median(phy)

49.5

In [9]:
marks = np.vstack((phy, mat))
marks

array([[56.7, 51.7, 63.6, ..., 31.2, 48.3, 53.4],
       [41.5, 50.2, 41.4, ..., 37.9, 40.2, 51.1]])

In [10]:
np.mean(marks, axis=1)

array([49.3679, 48.1866])

In [11]:
np.mean(marks, axis=0)

array([49.1 , 50.95, 52.5 , 44.6 , 48.3 , 50.3 , 53.35, 40.7 , 36.2 ,
       60.4 , 57.1 , 52.85, 44.7 , 42.65, 43.85, 43.9 , 49.55, 47.  ,
       50.05, 51.95, 52.75, 40.45, 40.9 , 46.15, 51.6 , 48.65, 40.3 ,
       46.95, 57.95, 54.5 , 39.35, 46.2 , 53.5 , 45.55, 54.95, 33.2 ,
       50.8 , 47.  , 55.7 , 51.4 , 54.65, 52.85, 55.55, 51.  , 39.4 ,
       46.3 , 53.8 , 53.8 , 49.75, 48.7 , 37.1 , 38.  , 45.1 , 56.65,
       46.8 , 50.75, 49.9 , 50.35, 55.15, 45.65, 46.8 , 50.25, 66.6 ,
       50.95, 49.6 , 36.5 , 39.7 , 52.55, 50.2 , 49.75, 48.9 , 52.25,
       50.65, 43.35, 55.9 , 40.85, 42.  , 47.6 , 50.3 , 52.85, 46.25,
       48.5 , 49.8 , 41.3 , 49.7 , 48.75, 51.3 , 52.  , 47.7 , 39.65,
       46.95, 39.5 , 39.95, 49.45, 55.6 , 57.9 , 49.55, 49.4 , 46.45,
       53.15, 45.5 , 51.35, 52.35, 42.  , 47.3 , 50.75, 53.7 , 45.8 ,
       42.6 , 47.75, 42.4 , 53.55, 53.55, 51.85, 39.9 , 51.15, 41.55,
       54.05, 49.1 , 48.8 , 51.15, 48.7 , 49.1 , 47.7 , 40.05, 46.55,
       45.1 , 58.2 ,

In [12]:
np.std(marks, axis=1)

array([7.91862612, 7.97801482])

In [13]:
phy[phy > np.mean(phy)]

array([56.7, 51.7, 63.6, 51. , 54.8, 56.5, 61.6, 60. , 50.4, 57.6, 56.9,
       55.5, 59.1, 55.7, 56.2, 61.7, 51.1, 58. , 53.9, 53. , 54.2, 53.1,
       60.4, 55.8, 51.7, 59.6, 49.4, 58.7, 57.5, 50.8, 54.8, 56.2, 55.6,
       55.8, 50.6, 71.6, 51. , 50.8, 53.3, 58.5, 53.1, 51.5, 58.6, 54.7,
       54.5, 55. , 53.5, 51. , 49.9, 53.9, 58.6, 65.5, 52.3, 56.6, 61.7,
       55.6, 50.8, 52.3, 50.3, 50.6, 53.4, 61.7, 51.2, 58. , 51.9, 55.2,
       52.7, 52.7, 64.8, 50.1, 64.6, 53.4, 51.2, 51.9, 53.8, 51.4, 51. ,
       59.4, 58.3, 53.3, 54.1, 53.1, 55.4, 61.7, 55.1, 54.2, 67.9, 52.1,
       55. , 51. , 62.5, 69.2, 70. , 59.2, 52.3, 53. , 54.9, 55.3, 51.3,
       51.8, 56.2, 50.3, 51.7, 56.6, 52.2, 57.1, 55.3, 52.5, 50.1, 61.2,
       68.8, 66.4, 55.3, 54.6, 63.8, 57.4, 51.7, 51.9, 53.8, 53.1, 52.6,
       50.2, 49.9, 66.4, 54.4, 55.7, 60.7, 54.5, 49.6, 58.3, 58.2, 66.3,
       61.6, 52.7, 58.3, 51. , 56.6, 57.2, 51. , 58.4, 51.8, 54.8, 54.7,
       55.5, 67.1, 51. , 61.6, 56.1, 51.9, 51.9, 49

In [14]:
np.where(phy > mat, 1, -1)

array([ 1,  1,  1,  1,  1, -1,  1, -1,  1, -1,  1,  1, -1, -1,  1,  1,  1,
       -1, -1,  1, -1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1,
       -1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1,
        1, -1,  1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1,  1,  1, -1, -1,
        1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1, -1,
        1, -1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1, -1,  1,
       -1, -1,  1,  1,  1, -1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1,
        1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,
        1,  1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1, -1,
        1, -1,  1,  1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1, -1,
        1, -1,  1, -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1,
       -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,
        1,  1,  1,  1,  1

In [15]:
np.where(phy > phy.mean())

(array([  0,   1,   2,   4,   6,   9,  10,  11,  14,  15,  16,  19,  24,
         28,  29,  32,  33,  34,  36,  38,  39,  41,  42,  43,  46,  48,
         49,  53,  55,  56,  57,  58,  59,  60,  61,  62,  64,  67,  68,
         70,  71,  72,  79,  81,  82,  85,  86,  87,  91,  92,  94,  95,
         96,  97,  98, 102, 105, 106, 107, 109, 111, 113, 117, 118, 121,
        122, 123, 127, 128, 129, 130, 132, 134, 135, 136, 137, 138, 140,
        142, 145, 146, 147, 150, 151, 154, 157, 158, 159, 160, 162, 164,
        165, 166, 170, 172, 173, 174, 177, 178, 181, 183, 186, 187, 189,
        191, 193, 194, 199, 201, 202, 206, 209, 214, 217, 221, 222, 223,
        224, 225, 227, 231, 233, 235, 236, 237, 238, 242, 243, 244, 248,
        249, 251, 252, 253, 254, 255, 257, 258, 260, 262, 264, 267, 269,
        270, 271, 272, 273, 274, 276, 277, 278, 279, 281, 283, 284, 286,
        287, 288, 290, 294, 300, 301, 306, 307, 308, 309, 310, 311, 313,
        314, 317, 318, 321, 322, 323, 325, 326, 328

In [16]:
grand_a = np.mean(phy) + 20
grand_b = np.mean(phy)
np.select([phy >= grand_a, np.logical_and(phy >= grand_b, phy < grand_a)], ['A', 'B'], default='C')

array(['B', 'B', 'B', 'C', 'B', 'C', 'B', 'C', 'C', 'B', 'B', 'B', 'C',
       'C', 'B', 'B', 'B', 'C', 'C', 'B', 'C', 'C', 'C', 'C', 'B', 'C',
       'C', 'C', 'B', 'B', 'C', 'C', 'B', 'B', 'B', 'C', 'B', 'C', 'B',
       'B', 'C', 'B', 'B', 'B', 'C', 'C', 'B', 'C', 'B', 'B', 'C', 'C',
       'C', 'B', 'C', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'C', 'B',
       'C', 'C', 'B', 'B', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C',
       'C', 'B', 'C', 'B', 'B', 'C', 'C', 'B', 'B', 'B', 'C', 'C', 'C',
       'B', 'B', 'C', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'B', 'C',
       'C', 'B', 'B', 'B', 'C', 'B', 'C', 'B', 'C', 'B', 'C', 'C', 'C',
       'B', 'B', 'C', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'B', 'B', 'B',
       'B', 'C', 'B', 'C', 'B', 'B', 'B', 'B', 'B', 'C', 'B', 'C', 'B',
       'C', 'C', 'B', 'B', 'B', 'C', 'C', 'B', 'B', 'C', 'C', 'B', 'C',
       'C', 'B', 'B', 'B', 'B', 'C', 'B', 'C', 'B', 'B', 'A', 'C', 'C',
       'C', 'B', 'C', 'B', 'B', 'B', 'C', 'C', 'B', 'B', 'C', 'C

In [17]:
np.piecewise(phy, [phy > grand_a, np.logical_and(phy >= grand_b, phy < grand_a)], [100, 60])

array([ 60.,  60.,  60.,   0.,  60.,   0.,  60.,   0.,   0.,  60.,  60.,
        60.,   0.,   0.,  60.,  60.,  60.,   0.,   0.,  60.,   0.,   0.,
         0.,   0.,  60.,   0.,   0.,   0.,  60.,  60.,   0.,   0.,  60.,
        60.,  60.,   0.,  60.,   0.,  60.,  60.,   0.,  60.,  60.,  60.,
         0.,   0.,  60.,   0.,  60.,  60.,   0.,   0.,   0.,  60.,   0.,
        60.,  60.,  60.,  60.,  60.,  60.,  60., 100.,   0.,  60.,   0.,
         0.,  60.,  60.,   0.,  60.,  60.,  60.,   0.,   0.,   0.,   0.,
         0.,   0.,  60.,   0.,  60.,  60.,   0.,   0.,  60.,  60.,  60.,
         0.,   0.,   0.,  60.,  60.,   0.,  60.,  60.,  60.,  60.,  60.,
         0.,   0.,   0.,  60.,   0.,   0.,  60.,  60.,  60.,   0.,  60.,
         0.,  60.,   0.,  60.,   0.,   0.,   0.,  60.,  60.,   0.,   0.,
        60.,  60.,  60.,   0.,   0.,   0.,  60.,  60.,  60.,  60.,   0.,
        60.,   0.,  60.,  60.,  60.,  60.,  60.,   0.,  60.,   0.,  60.,
         0.,   0.,  60.,  60.,  60.,   0.,   0.,  6