## P61-68  
## 矢量运算

In [1]:
import numpy as np
import math
f1 = np.array([10*math.cos(math.pi/6), 10*math.sin(math.pi/6)])
f2 = np.array([0, 12])
f = f1 + f2
f

array([ 8.66025404, 17.        ])

In [2]:
np.sqrt(np.sum(f**2))

19.078784028338912

In [3]:
np.linalg.norm(f)

19.078784028338912

In [4]:
f = np.array([6*math.cos(math.pi/6), 6*math.sin(math.pi/6)])
s = np.array([10, 0])
np.dot(f, s)

51.96152422706632

In [5]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
np.dot(c, d)

array([[19, 22],
       [43, 50]])

In [6]:
np.inner(f, s)

51.96152422706632

In [7]:
 np.inner(c, d)

array([[17, 23],
       [39, 53]])

In [8]:
ab = np.array([4, 1])
ac = np.array([1, 2])
s = np.cross(ab, ac) / 2
s

3.5

In [9]:
v = np.array([1,2,3])
b = np.array([9, 8, 7])
np.cross(v, b)

array([-10,  20, -10])

In [10]:
np.cross(c, d)

array([-4, -4])

In [11]:
v

array([1, 2, 3])

In [12]:
b

array([9, 8, 7])

In [13]:
np.outer(v, b)

array([[ 9,  8,  7],
       [18, 16, 14],
       [27, 24, 21]])

In [14]:
a = np.arange(6).reshape(2, 3)
b = np.arange(9).reshape(3, 3)
np.dot(a, b)

array([[15, 18, 21],
       [42, 54, 66]])

In [15]:
np.tensordot(a, b, axes=([1], [0]))

array([[15, 18, 21],
       [42, 54, 66]])

In [16]:
a = np.random.randint(2, size=(2, 6, 5))
b = np.random.randint(2, size=(3, 2, 4))

In [17]:
np.dot(a, b)

ValueError: shapes (2,6,5) and (3,2,4) not aligned: 5 (dim 2) != 2 (dim 1)

In [18]:
np.tensordot(a, b, axes=([0], [1])).shape

(6, 5, 3, 4)

In [19]:
c = np.random.randint(2, size=(2,3,5))
d = np.random.randint(2, size=(3,2,4))
np.tensordot(c, d, axes=((0, 1), (1, 0)))

array([[3, 0, 4, 3],
       [3, 1, 3, 3],
       [2, 0, 3, 2],
       [0, 0, 0, 0],
       [3, 1, 3, 3]])

In [20]:
np.tensordot(c, d, axes=((0, 1), (1, 0))).shape

(5, 4)