np.poly1d()函数，以一维数组为参数，创建多项式 $f(x)=x^2-2x+1$

In [94]:
import numpy as np
a = np.array([1, -2, 1])
p = np.poly1d(a)
p

poly1d([ 1, -2,  1])

In [95]:
type(p)

numpy.lib.polynomial.poly1d

计算f(1)

In [96]:
p(1)

0

In [97]:
g = np.poly1d([1, 3, 1])
f = lambda x:g(x-1)
f(0.0)

-1.0

In [98]:
f(1)

1

In [99]:
p2 = np.poly1d(a, r=True)
p2

poly1d([ 1.,  0., -3.,  2.])

In [100]:
print(p2)

   3
1 x - 3 x + 2


In [101]:
p2(1)

0.0

In [102]:
p2(-2)

0.0

In [103]:
p3 = np.poly1d(a, variable="m")
print(p3)

   2
1 m - 2 m + 1


In [104]:
print("p=", p)
print("p2=", p2)

p=    2
1 x - 2 x + 1
p2=    3
1 x - 3 x + 2


In [105]:
print(p + p2)

   3     2
1 x + 1 x - 5 x + 3


In [106]:
print(p - p2)

    3     2
-1 x + 1 x + 1 x - 1


In [107]:
print(p * p2)

   5     4     3     2
1 x - 2 x - 2 x + 8 x - 7 x + 2


In [108]:
p2 / p

(poly1d([1., 2.]), poly1d([0.]))

In [109]:
p4 = p2 + [-2, 1]
p5 = p2 * np.array([3,2,1])
print(p4)
print(p5)

   3
1 x - 5 x + 3
   5     4     3
3 x + 2 x - 8 x + 1 x + 2


In [110]:
p5 / [2, 3, 4]

(poly1d([ 1.5   , -1.25  , -5.125 , 10.1875]), poly1d([ -9.0625, -38.75  ]))

In [111]:
p.deriv() #微分

poly1d([ 2, -2])

In [112]:
p.integ() #积分

poly1d([ 0.33333333, -1.        ,  1.        ,  0.        ])

In [113]:
p.integ().deriv()

poly1d([ 1., -2.,  1.])

In [114]:
 np.roots(p4) 

array([-2.49086362,  1.83424318,  0.65662043])

In [115]:
r = np.array([1, -1])
fr = np.poly(r)  # np.poly()函数得到多项式的系数
fr

array([ 1.,  0., -1.])

In [116]:
print(np.poly1d(fr))

   2
1 x - 1


In [117]:
x = np.linspace(0, 2*np.pi, 10000)
y = np.sin(x)

In [118]:
f3 = np.polyfit(x, y, 3)
f5 = np.polyfit(x, y, 5)
f7 = np.polyfit(x, y, 7)

In [119]:
space3 = np.abs(np.polyval(f3, x) - y)

In [120]:
pf3 = np.poly1d(f3)
pf3(x)

array([-0.203109  , -0.2019105 , -0.20071271, ...,  0.20071271,
        0.2019105 ,  0.203109  ])

In [121]:
np.polyval(f3, x)

array([-0.203109  , -0.2019105 , -0.20071271, ...,  0.20071271,
        0.2019105 ,  0.203109  ])

In [122]:
space5 = np.abs(np.polyval(f5, x) - y)
space7 = np.abs(np.polyval(f7, x) - y)

In [123]:
np.max(space3), np.max(space5), np.max(space7)

(0.2031089987777295, 0.0159437666153033, 0.0006625828771995891)

In [124]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)
x

array([2., 3.])